export const prods = [
  {id:1,name:'HD PTZ Studio Camera',cat:'Broadcasting',sku:'BCX-CAM-HD01',price:128000,orig:155000,badge:'Sale',em:'🎥',bg:'#0d1828',desc:'Professional HD PTZ camera with 20x optical zoom, NDI support, and low-latency output. Ideal for studio and live broadcast.',specs:[['Resolution','1920×1080 60fps'],['Zoom','20x Optical'],['Interface','HDMI / SDI / NDI'],['Pan/Tilt','±170° / ±90°']],stock:true,rat:4.8},
  {id:2,name:'FM Broadcast Processor 4CH',cat:'Broadcasting',sku:'BCX-FMP-004',price:89500,orig:null,badge:'New',em:'📻',bg:'#1a180d',desc:'4-channel FM broadcast audio processor with AGC, multiband compression, and stereo encoder.',specs:[['Channels','4'],['Input','AES/EBU, Analog'],['Output','Composite / MPX'],['Latency','< 1ms']],stock:true,rat:5.0},
  {id:3,name:'Digital Audio Mixer 16CH',cat:'Audio',sku:'BCX-DAW-16',price:42000,orig:null,badge:'Hot',em:'🎛',bg:'#180d1a',desc:'Professional 16-channel digital audio mixer with DSP effects, USB recording, and motorised faders.',specs:[['Channels','16 Mic / 4 Stereo'],['Effects','32-bit DSP'],['Connectivity','USB / AES'],['Display','7" Touchscreen']],stock:true,rat:4.7},
  {id:4,name:'RF Power Amplifier 100W',cat:'Spare Part',sku:'BCX-SP-RF100',price:12800,orig:15000,badge:'Sale',em:'⚡',bg:'#0d1520',desc:'OEM 100W solid-state RF power amplifier module for FM transmitters. Compatible with Harris, RVR, and Nautel units.',specs:[['Power Output','100W'],['Frequency','87.5–108 MHz'],['Efficiency','≥80%'],['Compatibility','Harris / RVR']],stock:true,rat:4.5},
  {id:5,name:'Rack Mount UPS 2KVA',cat:'Electronics',sku:'BCX-UPS-2K',price:34500,orig:null,badge:'New',em:'🔋',bg:'#0d1828',desc:'2KVA rack-mount online UPS with pure sine wave output, LCD display, and RS232/USB monitoring.',specs:[['Capacity','2000VA / 1800W'],['Type','Online Double Conversion'],['Battery','12V 9Ah x4'],['Runtime','30 min full load']],stock:true,rat:4.9},
  {id:6,name:'SDI to HDMI Converter',cat:'Electronics',sku:'BCX-CNV-SDI',price:6800,orig:8500,badge:'Sale',em:'🔌',bg:'#1a0d10',desc:'3G-SDI to HDMI converter with loop-through, audio de-embedding, and format auto-detect.',specs:[['Input','3G/HD/SD-SDI'],['Output','HDMI 1.4'],['Loop-Through','Yes (SDI)'],['Audio','2CH De-embed']],stock:true,rat:4.6},
  {id:7,name:'Omnidirectional Antenna FM',cat:'Broadcasting',sku:'BCX-ANT-OMN',price:22000,orig:null,badge:null,em:'📶',bg:'#0d1520',desc:'Commercial-grade circular polarised FM broadcast antenna with 3dBd gain. Wind-load rated for tower mounting.',specs:[['Gain','3 dBd'],['Polarisation','Circular'],['Impedance','50Ω'],['Power Rating','500W']],stock:false,rat:4.4},
  {id:8,name:'Transistor Kit 50pcs',cat:'Spare Part',sku:'BCX-SP-TR50',price:3200,orig:4000,badge:'Sale',em:'🔧',bg:'#180d10',desc:'Assorted broadcast-grade transistor kit — MRF, BLF and 2SC types. Ideal for FM transmitter repair.',specs:[['Qty','50 pieces'],['Types','MRF / BLF / 2SC'],['Application','FM Transmitter'],['Package','TO-220 / TO-3']],stock:true,rat:4.3},
  {id:9,name:'4K Video Capture Card',cat:'Video',sku:'BCX-VID-4K',price:18500,orig:22000,badge:'Trending',em:'📹',bg:'#0d1828',desc:'4K PCIe video capture card with HDMI 2.0 input, multi-channel audio, and OBS-compatible SDK.',specs:[['Resolution','4K UHD 60fps'],['Interface','PCIe x4'],['Input','HDMI 2.0'],['Audio','8CH Embedded']],stock:true,rat:4.8},
  {id:10,name:'On-Air Studio Clock LED',cat:'Broadcasting',sku:'BCX-CLK-LED',price:9200,orig:null,badge:'New',em:'🕐',bg:'#1a180d',desc:'Large format LED studio clock with GPS sync, countdown timer, NTP support, and On-Air relay output.',specs:[['Sync','GPS / NTP'],['Display','8" Red LED'],['Relay','On-Air Output'],['Accuracy','±1ms']],stock:true,rat:5.0},
  {id:11,name:'Audio DSP Processor 2U',cat:'Audio',sku:'BCX-DSP-2U',price:56000,orig:null,badge:null,em:'🎚',bg:'#180d1a',desc:'Professional 2U DSP audio processor with 32-band parametric EQ, dynamics, AES67 and Dante networking.',specs:[['Channels','8 in / 8 out'],['EQ','32-band Parametric'],['Network','AES67 / Dante'],['Control','Web / RS232']],stock:true,rat:4.7},
  {id:12,name:'Coaxial Cable 50m Roll',cat:'Spare Part',sku:'BCX-CBL-RG6',price:1850,orig:2400,badge:'Sale',em:'🔄',bg:'#0d1520',desc:'Professional-grade RG-6 coaxial cable roll. Double-shielded with copper braid, low-loss up to 3GHz.',specs:[['Length','50 Metres'],['Impedance','75Ω'],['Frequency','DC – 3 GHz'],['Loss','2.6 dB/100m']],stock:true,rat:4.2},
];
